-- MySQL Script generated by MySQL Workbench
-- Mon Oct 16 23:49:43 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema e21803762_db1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema e21803762_db1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `e21803762_db1` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `e21803762_db1` ;

-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_compte_cpt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_compte_cpt` (
  `id_cpt` INT(11) NOT NULL,
  `pseudo_cpt` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `mdp_cpt` CHAR(64) NOT NULL,
  PRIMARY KEY (`pseudo_cpt`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_profil_pfl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_profil_pfl` (
  `nom_pfl` VARCHAR(45) NOT NULL,
  `prenom_pfl` VARCHAR(45) NOT NULL,
  `role_pfl` CHAR(1) NOT NULL,
  `etat_pfl` CHAR(1) NOT NULL,
  `pseudo_cpt` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  UNIQUE INDEX `pseudo_cpt_UNIQUE` (`pseudo_cpt` ASC),
  CONSTRAINT `fk_t_profil_pfl_t_compte_cpt1`
    FOREIGN KEY (`pseudo_cpt`)
    REFERENCES `e21803762_db1`.`t_compte_cpt` (`pseudo_cpt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_actualite_act`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_actualite_act` (
  `id_act` INT(11) NOT NULL AUTO_INCREMENT,
  `intitule_act` VARCHAR(100) NOT NULL,
  `description_act` VARCHAR(200) NOT NULL,
  `date_act` DATE NOT NULL,
  `pseudo_cpt` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  PRIMARY KEY (`id_act`),
  INDEX `fk_t_actualite_act_t_compte_cpt1_idx` (`pseudo_cpt` ASC),
  CONSTRAINT `fk_t_actualite_act_t_compte_cpt1`
    FOREIGN KEY (`pseudo_cpt`)
    REFERENCES `e21803762_db1`.`t_compte_cpt` (`pseudo_cpt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_scenario_sce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_scenario_sce` (
  `id_sce` INT NOT NULL AUTO_INCREMENT,
  `intitule_sce` VARCHAR(100) NOT NULL,
  `code_sce` VARCHAR(15) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `description_sce` VARCHAR(200) NOT NULL,
  `image_sce` VARCHAR(100) NOT NULL,
  `pseudo_cpt` VARCHAR(45) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NULL,
  PRIMARY KEY (`id_sce`),
  INDEX `fk_t_scenario_sce_t_compte_cpt1_idx` (`pseudo_cpt` ASC),
  CONSTRAINT `fk_t_scenario_sce_t_compte_cpt1`
    FOREIGN KEY (`pseudo_cpt`)
    REFERENCES `e21803762_db1`.`t_compte_cpt` (`pseudo_cpt`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_etape_eta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_etape_eta` (
  `id_eta` INT NOT NULL AUTO_INCREMENT,
  `question_eta` VARCHAR(45) NOT NULL,
  `reponse_eta` VARCHAR(45) NOT NULL,
  `ressource_eta` VARCHAR(100) NOT NULL,
  `intitule_eta` VARCHAR(45) NOT NULL,
  `code_eta` CHAR(8) CHARACTER SET 'utf8' COLLATE 'utf8_bin' NOT NULL,
  `ordre_eta` INT NOT NULL,
  `id_sce` INT NOT NULL,
  PRIMARY KEY (`id_eta`),
  INDEX `fk_t_etape_eta_t_scenario_sce1_idx` (`id_sce` ASC),
  UNIQUE INDEX `code_eta_UNIQUE` (`code_eta` ASC),
  CONSTRAINT `fk_t_etape_eta_t_scenario_sce1`
    FOREIGN KEY (`id_sce`)
    REFERENCES `e21803762_db1`.`t_scenario_sce` (`id_sce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_indice_ind`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_indice_ind` (
  `id_ind` INT NOT NULL AUTO_INCREMENT,
  `description_ind` VARCHAR(45) NOT NULL,
  `difficulte_ind` VARCHAR(45) NOT NULL,
  `lien_ind` VARCHAR(100) NOT NULL,
  `etape_id` INT NOT NULL,
  PRIMARY KEY (`id_ind`),
  INDEX `fk_t_indice_ind_t_etape_eta1_idx` (`etape_id` ASC),
  CONSTRAINT `fk_t_indice_ind_t_etape_eta1`
    FOREIGN KEY (`etape_id`)
    REFERENCES `e21803762_db1`.`t_etape_eta` (`id_eta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_participant_par`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_participant_par` (
  `id_par` INT NOT NULL AUTO_INCREMENT,
  `adresse_par` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_par`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `e21803762_db1`.`t_reussite_reu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `e21803762_db1`.`t_reussite_reu` (
  `id_par` INT NOT NULL,
  `id_sce` INT NOT NULL,
  `dateFirstR_reu` DATE NOT NULL,
  `dateSecondR_reu` DATE NOT NULL,
  `difficulte_reu` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_par`, `id_sce`),
  INDEX `fk_t_participant_par_has_t_scenario_sce_t_scenario_sce1_idx` (`id_sce` ASC),
  INDEX `fk_t_participant_par_has_t_scenario_sce_t_participant_par1_idx` (`id_par` ASC),
  CONSTRAINT `fk_t_participant_par_has_t_scenario_sce_t_participant_par1`
    FOREIGN KEY (`id_par`)
    REFERENCES `e21803762_db1`.`t_participant_par` (`id_par`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_t_participant_par_has_t_scenario_sce_t_scenario_sce1`
    FOREIGN KEY (`id_sce`)
    REFERENCES `e21803762_db1`.`t_scenario_sce` (`id_sce`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
